### ISSUE TITLE
capacity overflow error on `cyme --lsusb --verbose` on cyme 1.8.0 macOS

### ISSUE THREAD

**Issue by nervous-inhuman** [tuna-f1sh/cyme#25]
After updating to 1.8.0 (and switching over to the homebrew-core), I'm getting the following error when running cyme with `--lsusb` and `--verbose` options on macOS 14.5 (23F79)

```
...
thread 'main' panicked at library/alloc/src/raw_vec.rs:25:5:
capacity overflow
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Running with `RUST_BACKTRACE=full`
```
thread 'main' panicked at library/alloc/src/raw_vec.rs:25:5:
capacity overflow
stack backtrace:
   0:        0x1030eea88 - __mh_execute_header
   1:        0x102ec37e0 - __mh_execute_header
   2:        0x1030dff9c - __mh_execute_header
   3:        0x1030ee784 - __mh_execute_header
   4:        0x1030ec238 - __mh_execute_header
   5:        0x1030ed360 - __mh_execute_header
   6:        0x1030eee50 - __mh_execute_header
   7:        0x1030eede4 - __mh_execute_header
   8:        0x1030ec3c8 - __mh_execute_header
   9:        0x1030f4098 - __mh_execute_header
  10:        0x102e93bdc - __mh_execute_header
  11:        0x102e93b74 - __mh_execute_header
  12:        0x102f6cb54 - __mh_execute_header
  13:        0x102f68fec - __mh_execute_header
  14:        0x102e6dc64 - __mh_execute_header
```

**Comment by tuna-f1sh** [comment]
Sounds like I missed a bitshift of a u8 beyond its type porting some lsusb code - was hard to cover it all. 

Can you list the devices you have attached with `cyme --tree -vvv` so I have an idea what descriptor to look at?

**Comment by tuna-f1sh** [comment]
Thanks. Since it panics after ‘VCONN Power’ it must be this https://github.com/tuna-f1sh/cyme/blob/main/src/lsusb/bos_dumps.rs#L241 - the slice is a fixed `[u8; 32]` so I believe the code is valid but need to think deeper.

I forgot to ask for the `—json` flag for the dump without lsusb (`cyme —tree -vvv —json`), that way I can run it on my machine to test a fix.

**Comment by tuna-f1sh** [comment]
Actually, I see what is the issue: the `dump_value` function `repeat` to get spaces. Since that String will be 95 bytes - long er than the width - the arg passed to `repeat` must be rolling over and so be > `usize::MAX` or something. I'll post a fix in a bit.

**Comment by tuna-f1sh** [comment]
Should be fixed with https://github.com/tuna-f1sh/cyme/commit/392e046a7351ab15b2dafd0b3d8d7f19a8148549
