### ISSUE TITLE
depends on non-free licensed crate

### ISSUE THREAD

**Issue by jonassmedegaard** [tuna-f1sh/cyme#49]
This project looks super cool, and I want to package it for official inclusion with Debian, but unfortunately I cannot, because
the author of the dependency crate `pci-ids` forbids inclusion in free-for-all distributions like Debian:
https://github.com/lienching/pci-ids.rs/blob/main/LICENSE

Please consider avoiding that crate, or at least make the dependency on it optional.

**Comment by jonassmedegaard** [comment]
Corresponding Debian discussion is [here](bugs.debian.org/1085871).

**Comment by jonassmedegaard** [comment]
The issue is now solved upstream, thanks to a swift response from the author of pci-ids at https://github.com/lienching/pci-ids.rs/issues/17

**Comment by tuna-f1sh** [comment]
Perfect, thanks for both opening and solving!
