### ISSUE TITLE
Failed to parse system conifg (sic)

### ISSUE THREAD

**Issue by pro-sumer** [tuna-f1sh/cyme#6]
Recently `cyme` is displaying this error:

```
Failed to parse system conifg at Some("/Users/rob/Library/Application Support/cyme"), using default: Error(No such file or directory (os error 2))
```

(at least fix the typo?)

**Comment by tuna-f1sh** [comment]
Sorry, that was due to a change of the system config logic so that it doesn’t exit on failing to parse a system config - I forgot to exclude NotFound, which is normal if the user hasn’t installed a config.

Also corrected typo.

Thanks for the report!
