### ISSUE TITLE
Truncate very long fields

### ISSUE THREAD

**Issue by dmezh** [tuna-f1sh/cyme#8]
Hey, amazing work on this; I like it a lot! I suggest truncating very long names and maybe other fields - motivating example:

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/54985569/220179969-dd13daf8-de95-4b4c-95d0-4a6d9b4d418c.png">

That one device with the extremely long name is pushing the serial column off to the side and hurting readability. I would prefer the name ends in a `...` after some default max, and a flag to never truncate.

**Comment by tuna-f1sh** [comment]
Yes this is a good idea. It's actually something I have in my list of features to implement - some terminal width detection and auto-scaling. But as you say, a fixed max also makes sense for descriptor strings.

I'll have a look into it next time I get chance.

**Comment by tuna-f1sh** [comment]
I had added this and whilst I was at it, added a default auto-width feature that will find the max based on terminal width. See: https://github.com/tuna-f1sh/cyme/releases/tag/v1.3.1
